"""add file fields

Revision ID: 0ca154c9f66d
Revises: 4d8127bd3882
Create Date: 2026-04-19 15:53:07.740929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca154c9f66d'
down_revision = '4d8127bd3882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
